apiVersion: v1
kind: Service
metadata:
  name: roundcubemail
  labels:
    service: roundcubemail
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
  selector:
    service: roundcubemail
